name: dev
spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://localhost:3306/gp
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    test2:
      jdbc-url: jdbc:mysql://localhost:3306/gp1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver